# Generated by Django 3.2.5 on 2021-07-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(max_length=300)),
                ('new_date', models.DateTimeField()),
                ('new_url', models.CharField(max_length=300)),
            ],
        ),
    ]
